# Site settings
title: domnikl
email: liebler.dominik@gmail.com
description: "software, landscapes, guitars & whisky"
baseurl: "" # the subpath of your site, e.g. /blog/
copyright: "2016 by Dominik Liebler"
author: Dominik Liebler
permalink: :title/
url: "https://domnikl.github.io" # the base hostname & protocol for your site
twitter_username: domnikl
github_username:  domnikl

# Build settings
markdown: kramdown
